services:
  # Web Service
  - type: web
    name: quantitymeasurement-api
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /health
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: DATABASE_URL
        value: postgresql://quantitymeasurementdb_zueb_user:dfpSD1O3C4uBQTEN0hq3ZLJtuQ94NhtT@dpg-d7adklh5pdvs73dd9i60-a.oregon-postgres.render.com/quantitymeasurementdb_zueb
      - key: JWT_SECRET
        generateValue: true
